features = [
  "clock",
  "connectivity",
  "memory",
  "cpu",
  "gpu",
  "net_stats",
]

[connectivity]
glyph = "󰖩 "
idle = 1
format = "compact"
show_iface = true
show_route = true
show_dns = true
show_kind = true

[memory]
glyph = ""
idle = 1
output = "used"

[clock]
glyph = " "
format = "%a %d %b %Y %X %Z"
timezone = ""

[cpu]
glyph = ""
idle = 1
chip = "k10temp-pci-00c3"
report = "Tctl"

[gpu]
glyph = ""
idle = 1

[net_stats]
glyph = ""
idle = 1
ifaces = [
  "enp10s0",
  "wlx04d4c464bd3c",
]
